---
config:
  themeVariables:
    xyChart:
      plotColorPalette: "#e74c3c, #3498db"
---
xychart-beta
    title "Effort per Project: Arduino vs Zephyr"
    x-axis ["1st", "2nd", "3rd", "4th", "5th"]
    y-axis "Relative Effort" 0 --> 10
    line "Arduino" [3, 3, 3, 3, 3]
    line "Zephyr" [9, 5, 3, 2, 2]
